# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlindsController', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='window',
            options={'ordering': ('name', 'address', 'position')},
        ),
        migrations.AddField(
            model_name='window',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='window',
            name='batterylevel',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='window',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
